language: php
php:
  - '7.1'
sudo: false
services:
  - mysql
  - memcached
addons:
  chrome: stable
before_install:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database fusio;'
install:
  - composer create-project fusio/fusio fusio dev-master
  - npm install
  - node node_modules/grunt-cli/bin/grunt
  - node node_modules/protractor/bin/webdriver-manager update --versions.chrome 73.0.3683.68
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp .env fusio/.env
  - cp server.php fusio/public/server.php
  - cp -r dist fusio/public/fusio/
  - cp index.htm fusio/public/fusio/index.htm
  - pushd fusio/public
  - php server.php --warmup
  - (php -S 127.0.0.1:8008 server.php) &
  - popd
  - (node node_modules/protractor/bin/webdriver-manager start > /dev/null 2>&1) &
  - sleep 12
script:
  - node node_modules/protractor/bin/protractor tests/conf.js
